---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3120466604-bvMmXlYSGWSauOPAz3MxaTeyFoyvUntQP29OjdC
:access_token_secret: 5CK3x1vRGjcFaB2ws2bIKL84n1jX10wC1UvGV5KmrtdAF
